### ISSUE TITLE
Error while running script

### ISSUE THREAD

**Issue by snadi** [ThomasChuDesigns/Research_Task#1]
I followed all instructions and tried running the script with or without authentication, but I get the attached error
<img width="1920" alt="screen shot 2018-01-22 at 9 08 05 am" src="https://user-images.githubusercontent.com/2363957/35230639-d65ad012-ff53-11e7-8122-6fe4defeab0b.png">

**Comment by snadi** [comment]
@ThomasChuDesigns please check

**Comment by ThomasChuDesigns** [comment]
Hi Sarah,

I'm assuming you have python 3.5 or greater installed

It seems that your python command may be pointed to python 2, to check if that is the case run:
```python --version```
If that is the case, try running ``` python3 task.py ``` instead.

If the issue still occurs, you may need to create a new virtual environment using python3's built-in command:
``` python3 -m venv PATH```
and install the packages using pip3: ``` pip3 install -r requirements.txt ```
